spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: "root"
      password: "sql123123"
    url: "jdbc:mysql://localhost:3306/sesac?serverTimezone=UTC&characterEncoding=UTF-8"

